spring.application.name=campusos


#<--------DATABASE CONFIGURATION---------->
spring.datasource.url=jdbc:postgresql://localhost:5432/campusos
spring.datasource.username=postgres
spring.datasource.password=Sibbuuuu07

#<--------JPA / HIBERNATE CONFIGURATION--------->
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#<-------PostgreSQL Dialect------->
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#<---------SERVER CONFIGURATION--------->
server.port=8080
